{
  "Competitive Programming Template": {
    "prefix": "cpp",
    "body": [
      "/**",
      " * In the name of Allah, the Most Gracious, the Most Merciful",
      " * ---------------------",
      " * Author     : Al Kayes Rifat",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "#include<ext/pb_ds/assoc_container.hpp>",
      "#include<ext/pb_ds/tree_policy.hpp>",
      "using namespace __gnu_pbds;",
      "using namespace std;",
      "#define ordered_set tree<int, null_type,less_equal<int>, rb_tree_tag,tree_order_statistics_node_update>// - Use 'less<int>' for set, 'less_equal<int>' for multiset",
      "#define ll long long int",
      "#define ull unsigned long long",
      "#define nl \"\\n\"",
      "#define MOD 1000000007",
      "#define all(x) (x).begin(), (x).end()",
      "#define rall(x) (x).rbegin(), (x).rend()",
      "#define yes cout << \"YES\" << '\\n'",
      "#define no cout << \"NO\" << '\\n'",
      "#define coutv(v) \\",
      "    for (auto it : v) \\",
      "        cout << it << ' '; \\",
      "    cout << '\\n';",
      "",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      "    $0",
      "",
      "    return 0;",
      "}"
    ],
    "description": "Template for competitive programming"
  },
  "Test Case - Competitive Programming Template": {
    "prefix": "testcpp",
    "body": [
      "/**",
      " * In the name of Allah, the Most Gracious, the Most Merciful",
      " * ---------------------",
      " * Author     : Al Kayes Rifat",
      " * Date       : ${CURRENT_DATE}/${CURRENT_MONTH}/${CURRENT_YEAR} (${CURRENT_DAY_NAME})",
      " * Time       : ${CURRENT_HOUR}:${CURRENT_MINUTE} ",
      " * ---------------------",
      " */",
      "",
      "#include<bits/stdc++.h>",
      "#include<ext/pb_ds/assoc_container.hpp>",
      "#include<ext/pb_ds/tree_policy.hpp>",
      "using namespace __gnu_pbds;",
      "using namespace std;",
      "#define ordered_set tree<int, null_type,less_equal<int>, rb_tree_tag,tree_order_statistics_node_update>// - Use 'less<int>' for set, 'less_equal<int>' for multiset",
      "#define ll long long int",
      "#define ull unsigned long long",
      "#define nl \"\\n\"",
      "#define MOD 1000000007",
      "#define all(x) (x).begin(), (x).end()",
      "#define rall(x) (x).rbegin(), (x).rend()",
      "#define yes cout << \"YES\" << '\\n'",
      "#define no cout << \"NO\" << '\\n'",
      "#define coutv(v) \\",
      "    for (auto it : v) \\",
      "        cout << it << ' '; \\",
      "    cout << '\\n';",
      "",
      "",
      "int main(){",
      "",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "",
      
      "    long long alkayesrifat ;",
      "    cin >>  alkayesrifat ;",
      "    while(alkayesrifat--)",
      "    {",
      "",
      "        $0",
      "",
      "    }",
      "",
      "    return 0;",
      "}"
    ],
    "description": "For Test Case"
  }
}
